/**
 * Presets: whole looks the admin can apply in one click, then keep editing.
 *
 * A preset only carries visual intent. Ordering, hidden sections and the
 * product's own name belong to the operator, not to a look, so applying a
 * preset leaves those alone.
 */

import { DEFAULT_THEME, type Theme } from "./tokens";

type DeepPartial<T> = {
  [K in keyof T]?: T[K] extends readonly unknown[] ? T[K] : T[K] extends object ? DeepPartial<T[K]> : T[K];
};

export interface Preset {
  id: string;
  name: string;
  description: string;
  /** Two colours drawn as the swatch in the preset picker. */
  swatch: [string, string, string];
  theme: DeepPartial<Theme>;
}

export const PRESETS: Preset[] = [
  {
    id: "mono",
    name: "Mono",
    description: "The house look. Black, white and the brand green, square corners, hairline rules, motion kept to what earns its place.",
    swatch: ["#ffffff", "#0a0a0a", "#17a34a"],
    theme: {},
  },
  {
    id: "usl",
    name: "USL Studio",
    description:
      "The studio site, brought inside. Archivo display type at editorial scale, a structural grid behind the page, momentum scroll, a cursor that reacts, and every section wiping up on approach.",
    swatch: ["#f7f7f5", "#0d0d0c", "#d8540f"],
    theme: {
      mode: "light",
      neutral: { hue: 60, saturation: 4 },
      light: {
        canvas: "#ffffff",
        surface: "#f7f7f5",
        surfaceMuted: "#efefec",
        line: "#d8d8d6",
        ink: "#0d0d0c",
        inkMuted: "#545450",
        accent: "#d8540f",
        accentInk: "#ffffff",
        positive: "#0d6a47",
        warning: "#b06008",
        danger: "#be2020",
        info: "#0d6a47",
        highlight: "#0d6a47",
      },
      dark: {
        canvas: "#0a0b0a",
        surface: "#141614",
        surfaceMuted: "#1d1f1d",
        line: "#2b2e2b",
        ink: "#f6f6f3",
        inkMuted: "#9ea09b",
        accent: "#ff7a29",
        accentInk: "#0a0b0a",
        positive: "#2aa872",
        warning: "#e29820",
        danger: "#f06c6c",
        info: "#2aa872",
        highlight: "#2aa872",
      },
      radius: { linked: true, base: 0, pill: 999 },
      border: { width: 1, strongWidth: 2, accentBar: 3, focusWidth: 2, style: "solid", softness: 0 },
      typography: {
        heading: "archivo",
        body: "archivo",
        mono: "mono",
        scale: 1,
        headingWeight: 700,
        headingTracking: -0.03,
        bodyLineHeight: 1.6,
        labelCaps: true,
        labelTracking: 0.16,
        displaySize: 1.25,
      },
      density: { scale: 1.08, gutter: 40, cardPadding: 28, controlHeight: 46, rowHeight: 56, metricHeight: 168 },
      motion: {
        enabled: true,
        intensity: 1.3,
        speed: 0.8,
        easing: "expo",
        reveal: true,
        stagger: true,
        hover: true,
        magnetic: true,
        pageTransition: true,
        counters: true,
        marquee: true,
        cursor: true,
        smoothScroll: true,
        parallax: true,
        pulse: true,
        underline: true,
      },
      effects: { shadow: 0, gridTexture: true, noise: false, gradients: false, glass: false, glow: false, scanlines: false, vignette: false },
    },
  },
  {
    id: "soft",
    name: "Soft",
    description: "Rounded, lifted and quiet. Generous corners, a real elevation scale, and motion with a little spring in it.",
    swatch: ["#f8fafc", "#1e293b", "#17a34a"],
    theme: {
      mode: "light",
      neutral: { hue: 215, saturation: 12 },
      light: {
        canvas: "#f6f8f7",
        surface: "#ffffff",
        surfaceMuted: "#eef2f0",
        line: "#dbe3df",
        ink: "#131a17",
        inkMuted: "#5d6b65",
        accent: "#17a34a",
        accentInk: "#ffffff",
        positive: "#17a34a",
        warning: "#c2760a",
        danger: "#dc4444",
        info: "#0e8f95",
        highlight: "#6d5ce7",
      },
      dark: {
        canvas: "#0b1210",
        surface: "#121a17",
        surfaceMuted: "#1a2420",
        line: "#28352f",
        ink: "#eef4f1",
        inkMuted: "#9aa8a2",
        accent: "#2fbf63",
        accentInk: "#04140a",
        positive: "#2fbf63",
        warning: "#e0a33a",
        danger: "#ef6f6f",
        info: "#3ec2b4",
        highlight: "#9b8cff",
      },
      radius: { linked: false, base: 12, card: 18, control: 12, input: 12, badge: 999, pill: 999 },
      border: { width: 1, strongWidth: 2, accentBar: 0, focusWidth: 2, style: "solid", softness: 35 },
      typography: {
        heading: "sans",
        body: "sans",
        mono: "mono",
        scale: 1,
        headingWeight: 700,
        headingTracking: -0.02,
        bodyLineHeight: 1.65,
        labelCaps: false,
        labelTracking: 0.02,
        displaySize: 0.95,
      },
      density: { scale: 1.05, gutter: 32, cardPadding: 26, controlHeight: 44, rowHeight: 56, metricHeight: 158 },
      motion: {
        enabled: true,
        intensity: 0.9,
        speed: 1.1,
        easing: "spring",
        reveal: true,
        stagger: true,
        hover: true,
        magnetic: false,
        pageTransition: true,
        counters: true,
        marquee: false,
        cursor: false,
        smoothScroll: false,
        parallax: false,
        pulse: true,
        underline: false,
      },
      effects: { shadow: 2, gridTexture: false, noise: false, gradients: true, glass: false, glow: false, scanlines: false, vignette: false },
    },
  },
  {
    id: "midnight",
    name: "Midnight",
    description: "Dark by default, with the brand green carrying the light. Soft corners, a faint glow on anything active.",
    swatch: ["#07100c", "#e9f2ed", "#2fbf63"],
    theme: {
      mode: "dark",
      neutral: { hue: 155, saturation: 8 },
      dark: {
        canvas: "#040a07",
        surface: "#0a1410",
        surfaceMuted: "#11201a",
        line: "#1e3329",
        ink: "#e9f2ed",
        inkMuted: "#8aa197",
        accent: "#2fbf63",
        accentInk: "#03130a",
        positive: "#2fbf63",
        warning: "#e0a33a",
        danger: "#f06868",
        info: "#3ec2b4",
        highlight: "#7ee0a3",
      },
      light: {
        canvas: "#f3f7f4",
        surface: "#ffffff",
        surfaceMuted: "#e8efea",
        line: "#cfdcd4",
        ink: "#08150e",
        inkMuted: "#4f6459",
        accent: "#0f7a37",
        accentInk: "#ffffff",
        positive: "#0f7a37",
        warning: "#a86a08",
        danger: "#c33636",
        info: "#0d7c76",
        highlight: "#166b3a",
      },
      radius: { linked: true, base: 8, pill: 999 },
      border: { width: 1, strongWidth: 2, accentBar: 3, focusWidth: 2, style: "solid", softness: 20 },
      typography: {
        heading: "grotesk",
        body: "sans",
        mono: "mono",
        scale: 1,
        headingWeight: 700,
        headingTracking: -0.03,
        bodyLineHeight: 1.6,
        labelCaps: true,
        labelTracking: 0.1,
        displaySize: 1.05,
      },
      density: { scale: 1, gutter: 32, cardPadding: 24, controlHeight: 44, rowHeight: 52, metricHeight: 152 },
      motion: {
        enabled: true,
        intensity: 1,
        speed: 1,
        easing: "expo",
        reveal: true,
        stagger: true,
        hover: true,
        magnetic: false,
        pageTransition: true,
        counters: true,
        marquee: false,
        cursor: false,
        smoothScroll: false,
        parallax: false,
        pulse: true,
        underline: true,
      },
      effects: { shadow: 1, gridTexture: true, noise: false, gradients: false, glass: true, glow: true, scanlines: false, vignette: true },
    },
  },
  {
    id: "terminal",
    name: "Terminal",
    description: "Monospace throughout, phosphor green on near black, zero corners and motion that snaps rather than glides.",
    swatch: ["#050705", "#c8f7d4", "#3ef07a"],
    theme: {
      mode: "dark",
      neutral: { hue: 140, saturation: 10 },
      dark: {
        canvas: "#050705",
        surface: "#0a0f0b",
        surfaceMuted: "#101710",
        line: "#1f2d21",
        ink: "#c8f7d4",
        inkMuted: "#6f9a7c",
        accent: "#3ef07a",
        accentInk: "#03140a",
        positive: "#3ef07a",
        warning: "#e8d44a",
        danger: "#ff5f56",
        info: "#4ae0d0",
        highlight: "#9af7b8",
      },
      light: {
        canvas: "#f4f7f4",
        surface: "#ffffff",
        surfaceMuted: "#e9efe9",
        line: "#c9d6cb",
        ink: "#08130b",
        inkMuted: "#4d6152",
        accent: "#0b7a33",
        accentInk: "#ffffff",
        positive: "#0b7a33",
        warning: "#8a6d05",
        danger: "#c02626",
        info: "#0a7a72",
        highlight: "#0b7a33",
      },
      radius: { linked: true, base: 0, pill: 0 },
      border: { width: 1, strongWidth: 1, accentBar: 2, focusWidth: 2, style: "solid", softness: 0 },
      typography: {
        heading: "mono",
        body: "mono",
        mono: "mono",
        scale: 0.95,
        headingWeight: 600,
        headingTracking: -0.01,
        bodyLineHeight: 1.55,
        labelCaps: true,
        labelTracking: 0.14,
        displaySize: 0.9,
      },
      density: { scale: 0.92, gutter: 24, cardPadding: 18, controlHeight: 40, rowHeight: 44, metricHeight: 132 },
      motion: {
        enabled: true,
        intensity: 0.5,
        speed: 1.9,
        easing: "linear",
        reveal: true,
        stagger: true,
        hover: true,
        magnetic: false,
        pageTransition: false,
        counters: true,
        marquee: true,
        cursor: false,
        smoothScroll: false,
        parallax: false,
        pulse: true,
        underline: true,
      },
      effects: { shadow: 0, gridTexture: true, noise: true, gradients: false, glass: false, glow: true, scanlines: true, vignette: true },
    },
  },
  {
    id: "editorial",
    name: "Editorial",
    description: "Serif headlines, roomy measure, sentence case labels. Reads like a report rather than a console.",
    swatch: ["#fbfaf7", "#1a1815", "#16653a"],
    theme: {
      mode: "light",
      neutral: { hue: 40, saturation: 8 },
      light: {
        canvas: "#fbfaf7",
        surface: "#ffffff",
        surfaceMuted: "#f2f0ea",
        line: "#ddd8cd",
        ink: "#1a1815",
        inkMuted: "#635e54",
        accent: "#16653a",
        accentInk: "#ffffff",
        positive: "#16653a",
        warning: "#9a6a10",
        danger: "#a83232",
        info: "#1a6a72",
        highlight: "#6b4b8f",
      },
      dark: {
        canvas: "#12110e",
        surface: "#1a1815",
        surfaceMuted: "#232019",
        line: "#332f27",
        ink: "#f4f1e9",
        inkMuted: "#a8a094",
        accent: "#3fae70",
        accentInk: "#0a1a10",
        positive: "#3fae70",
        warning: "#d4a442",
        danger: "#e07070",
        info: "#48b3ba",
        highlight: "#b193d6",
      },
      radius: { linked: true, base: 2, pill: 999 },
      border: { width: 1, strongWidth: 2, accentBar: 2, focusWidth: 2, style: "solid", softness: 15 },
      typography: {
        heading: "serif",
        body: "sans",
        mono: "mono",
        scale: 1.05,
        headingWeight: 600,
        headingTracking: -0.015,
        bodyLineHeight: 1.75,
        labelCaps: false,
        labelTracking: 0.01,
        displaySize: 1.15,
      },
      density: { scale: 1.15, gutter: 40, cardPadding: 30, controlHeight: 44, rowHeight: 60, metricHeight: 168, maxWidth: 1500 },
      motion: {
        enabled: true,
        intensity: 0.8,
        speed: 0.85,
        easing: "standard",
        reveal: true,
        stagger: true,
        hover: true,
        magnetic: false,
        pageTransition: true,
        counters: true,
        marquee: false,
        cursor: false,
        smoothScroll: true,
        parallax: false,
        pulse: true,
        underline: true,
      },
      effects: { shadow: 1, gridTexture: false, noise: true, gradients: false, glass: false, glow: false, scanlines: false, vignette: false },
    },
  },
  {
    id: "brutal",
    name: "Brutal",
    description: "Thick rules, oversized headings, maximum contrast. Nothing soft, nothing decorative, everything loud.",
    swatch: ["#ffffff", "#000000", "#17a34a"],
    theme: {
      mode: "light",
      neutral: { hue: 0, saturation: 0 },
      light: {
        canvas: "#ffffff",
        surface: "#ffffff",
        surfaceMuted: "#ebebeb",
        line: "#000000",
        ink: "#000000",
        inkMuted: "#404040",
        accent: "#17a34a",
        accentInk: "#ffffff",
        positive: "#17a34a",
        warning: "#c26a00",
        danger: "#d61f1f",
        info: "#0b6f8f",
        highlight: "#000000",
      },
      dark: {
        canvas: "#000000",
        surface: "#0a0a0a",
        surfaceMuted: "#141414",
        line: "#ffffff",
        ink: "#ffffff",
        inkMuted: "#b0b0b0",
        accent: "#2fbf63",
        accentInk: "#000000",
        positive: "#2fbf63",
        warning: "#e8a33a",
        danger: "#ff5c5c",
        info: "#3fc7e0",
        highlight: "#ffffff",
      },
      radius: { linked: true, base: 0, pill: 0 },
      border: { width: 2, strongWidth: 3, accentBar: 8, focusWidth: 3, style: "solid", softness: 0 },
      typography: {
        heading: "archivo",
        body: "archivo",
        mono: "mono",
        scale: 1,
        headingWeight: 900,
        headingTracking: -0.05,
        bodyLineHeight: 1.5,
        labelCaps: true,
        labelTracking: 0.12,
        displaySize: 1.35,
      },
      density: { scale: 1, gutter: 28, cardPadding: 22, controlHeight: 48, rowHeight: 52, metricHeight: 158 },
      motion: {
        enabled: true,
        intensity: 1.2,
        speed: 1.5,
        easing: "quint",
        reveal: true,
        stagger: true,
        hover: true,
        magnetic: true,
        pageTransition: true,
        counters: true,
        marquee: true,
        cursor: false,
        smoothScroll: false,
        parallax: false,
        pulse: false,
        underline: true,
      },
      effects: { shadow: 0, gridTexture: false, noise: false, gradients: false, glass: false, glow: false, scanlines: false, vignette: false },
    },
  },
];

export const PRESET_IDS = PRESETS.map((p) => p.id);

function merge<T>(base: T, patch: unknown): T {
  if (patch === undefined) return base;
  if (Array.isArray(base) || patch === null || typeof patch !== "object" || typeof base !== "object" || base === null) {
    return patch as T;
  }
  const out = { ...(base as Record<string, unknown>) };
  for (const [key, value] of Object.entries(patch as Record<string, unknown>)) {
    out[key] = merge((base as Record<string, unknown>)[key], value);
  }
  return out as T;
}

/**
 * Applies a preset over the shipped defaults, then puts back the parts of the
 * current theme that describe the workspace rather than its appearance. Picking
 * a look should never rearrange the navigation or rename the product.
 */
export function applyPreset(current: Theme, presetId: string): Theme {
  const preset = PRESETS.find((p) => p.id === presetId);
  if (!preset) return current;
  const next = merge(DEFAULT_THEME, preset.theme) as Theme;
  return {
    ...next,
    preset: preset.id,
    layout: current.layout,
    brand: {
      ...next.brand,
      productName: current.brand.productName,
      wordmark: current.brand.wordmark,
      wordmarkAccent: current.brand.wordmarkAccent,
      tagline: current.brand.tagline,
    },
  };
}
